### ISSUE TITLE
Speed test no more running

### ISSUE THREAD

**Issue by mushuthecat** [adorobis/speedtest-CLI2mqtt#2]
Hello,

Since my last update my container is not working anymore

extract from docker logs

```
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'speedtest'
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 308, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 67, in run_speedtest
    process = subprocess.Popen([SPEEDTEST_PATH,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'speedtest'
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 308, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 67, in run_speedtest
    process = subprocess.Popen([SPEEDTEST_PATH,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'speedtest'
```

**Comment by adorobis** [comment]
Please update config.ini :
`SPEEDTEST_PATH=/usr/src/app/speedtest`
The Docker image is now based on alpine therefore with a custom cli install.
Sorry for breaking change.

**Comment by giig982** [comment]
Today I update to last docker alpine image (fd7872988f5f) and I have the same errors, even with `SPEEDTEST_PATH=/usr/src/app/speedtest `.

```
File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/speedtest'
Successfully connected to MQTT broker
Running Speedtest
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 319, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 67, in run_speedtest
    process = subprocess.Popen([SPEEDTEST_PATH,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/speedtest'
```

Moreover, I cannot find the previous image to try to revert to a previous one.

**Comment by adorobis** [comment]
Strange, could you please check the :latest image? It is also alpine based now

**Comment by giig982** [comment]
Based on the page https://hub.docker.com/r/adorobis/speedtest2mqtt/tags, the image with hash fd7872988f5f is the latest, and it's the same of the alpine one.

Anyway, I just checked out your repo and created an image by myself with your Dockerfile, and it's working again. I think I'll keep this for the moment.

**Comment by adorobis** [comment]
Sorry, I've just realized that I messed up with Docker file(s). Please pull again and it should work now.
