### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by mushuthecat** [adorobis/speedtest-CLI2mqtt#4]
Hello,

im facing to a new issue since few days:

```
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 312, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 84, in run_speedtest
    st_results = json.loads(stderr)
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 6 (char 5)
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 312, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 84, in run_speedtest
    st_results = json.loads(stderr)
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 6 (char 5)
Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 312, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 84, in run_speedtest
    st_results = json.loads(stderr)
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
```

Regards

**Comment by adorobis** [comment]
Do you still face it? I've just seen it in my logs as well logged yesterday but today it all works ok. I would assume the speedtest.net was not returning properly formatted data.

**Comment by mushuthecat** [comment]
Hi,

i solved my issue right by having a look to the speedtest.log
it seems that the server that i had setup in my config.ini failed is no more available after changing the value it seems to work thanks :D

**Comment by adorobis** [comment]
OK, great! It is interesting that the container log is showing something different than the speedtest.log :) But indeed it is much more meaningful there.

**Comment by mushuthecat** [comment]
Hi,

Since i edited the config.ini with another server id it works thanks

**Comment by adorobis** [comment]
Btw, I could not reproduce the error. If I enter a non existent server it would nicely log it in the speedtest.log file and update the Speedtest.net Status sensor with the error message in its attributes like below:
![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/19752098/0f5a1d49-35d6-4c23-b555-890e8d7e102b)

**Comment by mushuthecat** [comment]
Hi

I was using the serverd id: 24215 before solving my issue with a new one : 29544

this is the extract of my HA log files when the problem occured 

![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/83928911/3171ab8d-9ab4-4276-ba99-01731d37907a)
![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/83928911/da15b333-eeaa-4d3b-a3f8-d362443484e6)


Regards
